[WIP] Pool registration certificates
vacuumlabs/ledgerjs-cardano-shelley pull request #12
Opened 2020-10-11 22:51 UTC by janmazak

Does not fully work yet.

2020-10-14 18:15 UTC, xdzurman requested changes

2020-10-14 18:15 UTC, xdzurman commented on src/Ada.js
> +      if (withdrawals.length > 1)
should be either withdrawals.length > 0 or withdrawals.length >= 1 or just withdrawals.length

2020-10-14 21:44 UTC, janmazak commented
Should fully work now, apart from missing tests.

What about the too long address? I have replaced it in `poolCertificate.js`, but not in `integration/signTx.js`.

2020-10-19 15:50 UTC, PeterBenc commented on src/Ada.js
> +  vrfKeyHashHex: string,
Is this really a hash? From what I can see, this is 32 bytes long in parsed tx. Thus it should be something like `vrfPubKeyHex`...Right? Or is ledger expecting me to hash this?

2020-10-19 15:50 UTC, PeterBenc commented on src/Ada.js
> +  rewardAccountHashHex: string,
From what I can see, this has 29 bytes in parsed tx. Isnt this supposed to be called something like `rewardAccountAddressHex` ? Or `rewardAddressHex`? Or am I supposed to drop the first byte of the address?

2020-10-19 16:17 UTC, refi93 commented on src/Ada.js
> +  vrfKeyHashHex: string,
yes, the serialized transaction contains the blake2b-256 hash of the vrf key, even if the vrf key itself is 32 bytes as well. I just checked it and `echo -n aa0888b9da466f04cba88ee70cfc3dfc3df6ef53dea57a94f6762a253b3c21ab | xxd -r -p | b2sum -l 256 -b | awk '{print $1}'` yields the hash included in the sample tx in the hw wallet owner support design specs (https://docs.google.com/document/d/1H4MHj8AysiRg75bVx7xd3PouQWdGfgEDLUqQAn1TJy0/edit#heading=h.60fl10mfqiy9)

2020-10-19 16:29 UTC, janmazak commented on src/Ada.js
> +  rewardAccountHashHex: string,
No, it is the reward address. I've renamed the field.

2020-10-19 16:30 UTC, PeterBenc commented on src/Ada.js
> +  vrfKeyHashHex: string,
I see, I was automatically assuming its pubkey since its 32 bytes long. Thanks :+1:

2020-10-19 17:15 UTC, PeterBenc commented on src/Ada.js
> +  rewardAccountHashHex: string,
Sorry to bother you with this. You renamed it to `rewardAccountHex`. Didn't you mean `rewardAddressHex`?

2020-10-19 18:13 UTC, janmazak commented on src/Ada.js
> +  rewardAccountHashHex: string,
The stupid inconsistent terminology (by IOHK/Cardano) is behind this. Internally, we use reward address for ledger (as it is used in some of their specs). But in most discussions they favor "reward account", in some of the docs, too, so I decided that it would be better to call it account (hopefully avoiding confusion of Daedalus and other wallets).

2020-10-20 12:19 UTC, refi93 commented on package.json
> +    "test-pool": "yarn run build-test && yarn run test-pool-run",
pools should not have its own target in the final version and even now you can quite conveniently grep out the stakepool registration related tests by name, see comment below

```
"//": "run single test by specifying --grep <name> parameter in test-integration"
```

2020-10-20 12:22 UTC, refi93 commented on src/Ada.js
> +      Precondition.check(input.txHashHex.length == 32 * 2, "invalid tx hash");
this should be `===`, otherwise it's unnecessary susceptible for edge cases like '64' == 32*2 being true and similar as type conversion is happening in the background

2020-10-20 12:24 UTC, refi93 commented on src/Ada.js
> +      Precondition.check(input.txHashHex.length == 32 * 2, "invalid tx hash");
I see `==` being used in several other places not necessarily touched by this PR, so I would recommend refactoring those to `===` as well

2020-10-30 13:55 UTC, refi93 commented on src/cardano.js
> +  Precondition.checkIsArray(inputs, "outputs not an array");
the error message does not match the data being checked

2020-10-30 13:57 UTC, refi93 commented on src/cardano.js
> +    } else if (output.spendingPath) {
we probably shouldn't allow outputs given as paths for stakepool registrations as it may be abused to extract addresses from the transaction by the counterparty

2020-10-30 14:00 UTC, refi93 commented on src/cardano.js
> +    Precondition.checkIsUint32(stakingBlockchainPointer.blockIndex, "invalid blockchain pointer");
I would move the error message strings out to an object and reference the keys instead - it would allow for convenient reusing and less cluttered validation logic

2020-10-30 15:03 UTC, refi93 commented on src/Ada.js
> +        const mdResponse = await _send(
mdResponse is imho too cryptic of a name, I would name it metadataResponse

2020-10-30 15:11 UTC, refi93 commented on src/Ada.js
> +        Assert.assert(mdResponse.length === 0);
I see those assertions being introduced with this feature only, do we really need/want them and if so, it would make sense to wrap the _send function into an "expectEmptyResponse" helper function instead of asserting explicitly all the time.

But imho asserting on ledger responses in js is rather redundant given we already do that on the hw app layer and such situations should not happen in the first place provided ledger firmware/js is implemented properly with proper input validation.

2020-10-30 15:16 UTC, refi93 commented on src/cardano.js
> +    let ipParts = params.ipv6.split(':');
this can be condensed into 

```
ipv6Address.split(':').join('');
```

2020-10-30 20:20 UTC, refi93 requested changes
see comments

2020-11-01 16:16 UTC, janmazak commented on src/Ada.js
> +        Assert.assert(mdResponse.length === 0);
I've refactored the assertions. For each `_send` in tx signing, the length of the response is now asserted (not only the empty ones). It's not really needed, but checking buffer lengths is cheap, so I don't feel any urge to remove it altogether.

2020-11-02 14:54 UTC, refi93 commented on src/Ada.js
> +        Assert.assert(mdResponse.length === 0);
it clutters the code IMO, making it harder to read for future contributors. I agree there is no harm in the additional check, and we can retain it, but I would suggest introducing a _sendAndExpectEmptyResponse function which would encapsulate this behavior then (feel free to find some more suitable name)

2020-11-02 15:00 UTC, refi93 commented on src/Ada.js
> +        Assert.assert(mdResponse.length === 0);
sorry I see now that the repetitive assertions on response length dissapeared, so disregard my previous comment

2020-11-02 15:07 UTC, refi93 commented on src/Ada.js
> +    const _send = async function(p1, p2, data, expectedResponseLength = 0) {
I would make expectedResponseLength undefined by default and disable the assertion for the response length if its undefined - this way the call can be used even for variable length responses and it's imho not very intuitive to do such check by default, better have the developer explicitly enable it by making them pass the expected length explicitly

2020-11-02 15:25 UTC, janmazak commented on src/Ada.js
> +    const _send = async function(p1, p2, data, expectedResponseLength = 0) {
That's how I tried to write it at first, but for this particular case, all the responses have fixed length known in advance. So for a generic solution I would use the suggested way, but for signTransaction, I don't see much point in adding zeros: only two places use non-zero value and about a dozen or more use 0 for the length of the response.

2020-11-18 13:28 UTC, merged