Alonso
vacuumlabs/ledgerjs-cardano-shelley pull request #132
Opened 2021-09-22 12:49 UTC by mkv-vcm

2021-09-22 16:20 UTC, janmazak requested changes
Just a few quick comments before I forget them.

2021-09-22 16:20 UTC, janmazak commented on src/types/public.ts
>      destination: TxOutputDestination
I'd move this to be the first item in the object.

2021-09-22 16:20 UTC, janmazak commented on src/types/public.ts
> +    scriptDataHash?: string | null
I am against using "script" in this name, CDDL does not do it and formal specs also talk only about datum, no mention of scripts.

2021-09-22 16:20 UTC, janmazak commented on src/types/public.ts
> +    scriptDataHash?: string | null,
Usually, we use "hex" in the names of hex strings, e.g.
```
export type TxAuxiliaryDataArbitraryHashParams = {
    /** Hash of the transaction auxiliary data */
    hashHex: string
}
```

2021-09-23 07:29 UTC, mkv-vcm commented on src/types/public.ts
> +    scriptDataHash?: string | null
True, that explains the name collision misunderstanding in the Ledger code as well.

2021-09-23 08:03 UTC, mkv-vcm commented on src/types/public.ts
> +    scriptDataHash?: string | null,
Done.

2021-09-23 08:03 UTC, mkv-vcm commented on src/types/public.ts
>      destination: TxOutputDestination
Refactoring, but yeah, it was weird.

2021-11-02 10:39 UTC, janmazak requested changes

2021-11-02 10:39 UTC, janmazak commented on src/interactions/signTx.ts
> +  if (output.datumHashHex) {
```suggestion
  if (output.datumHashHex != null) {
```

2021-11-02 10:39 UTC, janmazak commented on src/interactions/signTx.ts
> +  if (output.datumHashHex) {
(to be consistent with other places like this, it distinguishes undefined and null from anything else; that way, we do not need to rely on validation to catch stuff like empty arrays)

2021-11-02 10:39 UTC, janmazak commented on src/interactions/signTx.ts
> +    SCRIPT_DATA_HASH = 0x34,
```suggestion
    DATUM_HASH = 0x34,
```

2021-11-02 10:39 UTC, janmazak commented on src/parsing/transaction.ts
> +        scriptDataHashHex: scriptDataHash,
```suggestion
        scriptDataHashHex,
```

2021-11-02 10:39 UTC, janmazak commented on src/parsing/transaction.ts
> +    const scriptDataHash = tx.scriptDataHashHex == null
```suggestion
    const scriptDataHashHex = tx.scriptDataHashHex == null
```

2021-11-02 10:39 UTC, janmazak commented on src/parsing/transaction.ts
> +        datumHashHex: datumHash,
```suggestion
        datumHashHex,
```

2021-11-02 10:39 UTC, janmazak commented on src/parsing/transaction.ts
> +    const datumHash = output.datumHashHex
```suggestion
    const datumHashHex = output.datumHashHex
```

2021-11-02 10:39 UTC, janmazak commented on src/parsing/transaction.ts
> +    const datumHash = output.datumHashHex
Also, let's write the ?: operator consitently with other cases, e.g.
```
const ttl = tx.ttl == null
        ? null
        : parseUint64_str(tx.ttl, {}, InvalidDataReason.TTL_INVALID)
```

2021-11-02 10:39 UTC, janmazak commented on test/integration/__fixtures__/signTx.ts
> +        // destination: destinations.multiassetThirdParty,
Can't the names be improved? They can be as long as we need to make them clear, hopefully without additional comments.

2021-11-02 10:39 UTC, janmazak commented on test/integration/__fixtures__/signTx.ts
> +  additionalWitnessPaths: BIP32Path[]
The trailing comma is not consistent here --- don't we have some eslint rule for that, actually? Or is it not applied here? (Perhaps consult with @KubqoA how to deal with it in some automated fashion.)

2021-11-02 10:39 UTC, janmazak commented on test/integration/__fixtures__/signTx.ts
> +        "d2c7763e9610c3440a8000cb6abfcf3f48d4ef713505066cea901a4ef576db16",
I think we should add a test checking for consistency: for each test, validate that txHashHex is correctly computed from txBody (perhaps at the beginning of running a test suite? that way, it will force us to update it, hopefully). Or just write the tests in such a way that that the correct result is computed from the given tx body? But that would be a bit annoying for debugging (one wants a quick way to manually compare the tx hash with ledger result).

Perhaps create a separate issue about this.

2021-11-03 07:10 UTC, mkv-vcm commented on test/integration/__fixtures__/signTx.ts
> +        // destination: destinations.multiassetThirdParty,
I guess they could be, though I'm not sure how to gauge exactly what is in the hashes.

2021-11-03 07:31 UTC, mkv-vcm commented on src/errors/invalidDataReason.ts
> +  SCRIPT_DATA_HASH_WRONG_LENGTH = "script data hash not 32 long",
Reminder for myself that there is another similar one in second phase.

2021-11-03 07:31 UTC, mkv-vcm commented on src/interactions/signTx.ts
> +  STAGE_SCRIPT_DATA_HASH = 0x0c,
That can be arranged.

2021-11-03 07:36 UTC, mkv-vcm commented on src/interactions/signTx.ts
> +  if (output.datumHashHex) {
Hmm, I'm not a hundred percent sure what the exact reasoning here is. One catches anything that is evaluates to false, including null and undefined, and the latter will only refuse undefined and null. What validations don't we want to rely on here? That member is already a FixlenHexString.

2021-11-03 07:37 UTC, mkv-vcm commented on src/interactions/signTx.ts
> +    SCRIPT_DATA_HASH = 0x34,
Done.

2021-11-03 07:38 UTC, mkv-vcm commented on src/parsing/transaction.ts
> +        datumHashHex: datumHash,
With one more line.

2021-11-03 07:39 UTC, mkv-vcm commented on src/parsing/transaction.ts
> +    const datumHash = output.datumHashHex
Ok.

2021-11-03 07:45 UTC, mkv-vcm commented on test/integration/__fixtures__/signTx.ts
> +        "d2c7763e9610c3440a8000cb6abfcf3f48d4ef713505066cea901a4ef576db16",
That's a neat idea for automation, I'm just a bit worried about bringing the hash calculating code into the JS side. It probably won't change, and if it does it's a huge breaking change for the whole infrastructure, but still, that feels like an internal thing. But definitely worth a look at.

2021-11-03 07:47 UTC, mkv-vcm commented on test/integration/__fixtures__/signTx.ts
> +        "d2c7763e9610c3440a8000cb6abfcf3f48d4ef713505066cea901a4ef576db16",
#142

2021-11-03 07:47 UTC, mkv-vcm commented on test/integration/__fixtures__/signTx.ts
> +  additionalWitnessPaths: BIP32Path[]
In progress with Jakub.

2021-11-22 09:05 UTC, janmazak reviewed
There are some unresolved comments here, e.g. the one about "in progress with Jakub".

2021-11-22 10:49 UTC, mkv-vcm commented on test/integration/__fixtures__/signTx.ts
> +        // destination: destinations.multiassetThirdParty,
Yeah, that'll be it I think, I can't really explain the hashes.

2021-11-22 11:59 UTC, janmazak commented on src/types/public.ts
> +     * and the exact same transaction creating different tx bodies and hashes might cause problems
Not entirely true, I'd use something like:
A flag indicating whether network id is part of the serialized tx body --- this depends on Ledger app version, not on the transaction itself (or other parameters of the signTransaction() call).

2021-11-22 11:59 UTC, janmazak commented on src/types/public.ts
> +     * and the exact same transaction creating different tx bodies and hashes might cause problems
Also, we should make this flag optional, and comment that if not given, it defaults to false (for backwards compatibility) --- please consult with David to make sure we are consistent with Trezor.

This will render `NetworkIdlessTestResult` unnecessary perhaps?

2022-01-12 14:06 UTC, janmazak commented
Will be merged via #136.

2022-01-12 14:06 UTC, closed without merging