implement reject tests and rejection parity
vacuumlabs/ledgerjs-cardano-shelley pull request #140
Opened 2021-11-01 13:20 UTC by mkv-vcm

The categorization is just following the security policies for now, if you have a better idea, it's more than welcome!

2021-11-12 17:52 UTC, janmazak commented on test/integration/__fixtures__/signTxRejects.ts
> +const poolRegParamOwner: PoolRegistrationParams = {
I'd consider separating pool registrations into a specific file (as we have with "positive" tests).

2021-11-12 17:52 UTC, janmazak commented on test/integration/__fixtures__/signTxRejects.ts
> +        errMsg: "Action rejected by Ledger's security policy",
Let's replace this with a symbolic constant, it is easier to refer to when adding new tests (e.g. for code completion), and more resistant to changes in the strings.

2021-11-15 08:27 UTC, mkv-vcm commented on test/integration/__fixtures__/signTxRejects.ts
> +        errMsg: "Action rejected by Ledger's security policy",
That's exactly what caught my eyes Friday afternoon, when refactoring the pool owner reject tests. Though a good place for this string constant is harder to find, but I'll figure something.

2021-11-15 08:44 UTC, mkv-vcm commented on test/integration/__fixtures__/signTxRejects.ts
> +const poolRegParamOwner: PoolRegistrationParams = {
They are quite interwoven with the other tests in many cases, since a lot of the operations are allowed with both pool and non-pool signingmodes. Right now, after the rebases and refactors, the pool owner validation tests are separate, what else tests would you think would be good to pull apart? stakePoolRegistrationPoolIdRejectTestcases and stakePoolRegistrationOwnerRejectTestcases are the ones that exclusively deal with pool registration cases.

2021-11-19 13:15 UTC, janmazak requested changes

2021-11-19 14:42 UTC, mkv-vcm commented on src/errors/invalidDataReason.ts
> +  SIGN_MODE_PLUTUS__CERTIFICATE_STAKE_CREDENTIAL_ONLY_AS_SCRIPT =
Yes, after we cleared up what kind of stake credentials are allowed in PLUTUS, this and the associated check and test became erroneous.

2021-11-19 14:43 UTC, mkv-vcm commented on src/parsing/transaction.ts
> +        type = destination.addressParams.type
Bad habits, in C you can't introduce a new variable without a scope and case doesn't create a scope in itself.

2021-11-19 14:45 UTC, mkv-vcm commented on src/parsing/transaction.ts
> +            !tx.collaterals || tx.collaterals.length == 0,
Actually, it's already unified by the parse function into an empty array. These are superfluous checks.

2021-11-22 11:46 UTC, janmazak commented on test/integration/__fixtures__/signTxPoolRegistration.ts
>          errMsg: "Action rejected by Ledger's security policy",
Something like
`errMsg: DeviceStatusMessages[DeviceStatusCodes.ERR_REJECTED_BY_POLICY]`
also here?

2021-11-22 11:46 UTC, janmazak commented on test/integration/__fixtures__/signTxRejects.ts
> +const poolRegParamOwner: PoolRegistrationParams = {
I'd put together `stakePoolRegistrationPoolIdRejectTestcases`, `stakePoolRegistrationOwnerRejectTestcases`, and `test/integration/signTxPoolRegistration.test.ts` together since all are pool registration reject tests (not sure into which file --- maybe it's enough to keep text fixtures separate, not the files executing the tests).

 And maybe refactor `test/integration/signTxPoolRegistration.test.ts` to be consistent with the "new" tests (not sure what exactly that means, but the test definitions just looks visually different).

2021-11-29 15:00 UTC, janmazak reviewed
`yarn lint` shows errors.

2021-11-29 15:00 UTC, janmazak commented on test/integration/__fixtures__/signTxPoolRegistration.ts
> +// export const withdrawals: Record<
Why is this commented out?

2021-11-29 15:00 UTC, janmazak commented on test/integration/signTxPoolRegistration.test.ts
> +describeRejects("signTxPoolRegistrationRejectOwner_Certifications", invalidCertificates)
```suggestion
describeRejects("signTxPoolRegistrationRejectOwner_Certificates", invalidCertificates)
```

2021-11-29 15:21 UTC, mkv-vcm commented on test/integration/__fixtures__/signTxPoolRegistration.ts
> +// export const withdrawals: Record<
This is a WIP (hence the "[WIP]" in the commit message), just put up so it's not lost if something goes wrong with my computer.
Probably will be removed, but I don't like to actually delete things until I'm sure it needs to be gone, too much hassle looking up from diffs.

2021-11-29 15:21 UTC, mkv-vcm commented on test/integration/signTxPoolRegistration.test.ts
> +describeRejects("signTxPoolRegistrationRejectOwner_Certifications", invalidCertificates)
The names will be quite different when I'm finished with this.

2022-02-10 16:35 UTC, merged