some tests for single accounting
vacuumlabs/ledgerjs-cardano-shelley pull request #143
Opened 2021-11-03 12:52 UTC by mkv-vcm

2021-11-03 13:27 UTC, janmazak approved these changes
CircleCI fails on `yarn lint`, otherwise OK.

2021-11-03 14:53 UTC, gabrielKerekes commented
I think it would be worth it to add all the tests which Trezor has so that we can be sure that all the combinations work as expected -> https://github.com/trezor/trezor-firmware/blob/master/common/tests/fixtures/cardano/sign_tx.failed.json#L1585. But maybe it can be considered an overkill for Ledger? What do you think @janmazak?

2021-11-03 23:21 UTC, janmazak requested changes
I've added a TODO describing what needs to be added.

2021-11-10 10:56 UTC, janmazak approved these changes

2021-11-10 11:14 UTC, merged