Added docs for exported endpoints
vacuumlabs/ledgerjs-cardano-shelley pull request #17
Opened 2020-12-02 10:55 UTC by jmuravsky

2020-12-02 17:50 UTC, refi93 commented on docs/getAddress.md
> +```
I would add a remark that in order to display the address to the user, additional conversion to bech32/base58 depending on the address era (Byron/Shelley) is required

2020-12-02 17:51 UTC, refi93 commented on docs/getAddress.md
> +    addressHex: '0x82D818582183581CCCB2A5AEBFF21CDE864D7B4604CE0F0720B819200315AE7834C6A6A5A0001AB0FC69CB'
I would add the base58 encoding of the address so the reader can easily cross-check their results

2020-12-02 17:53 UTC, refi93 commented on docs/signTransaction.md
> +* `path` - *required* `Array<number>` BIP44 derivation path for the staking address included in this certificate, minimum length `5`, accepts only Array (ex. `[(1852 | 0x80000000) >>> 0, (1815 | 0x80
with the stake pool registration support introduction the path parameter became optional, just so you know when you would be extending the docs

2020-12-02 17:54 UTC, refi93 commented on docs/signTransaction.md
> +* `path` - *required* `Array<number>` BIP44 derivation path for the address, minimum length `5`, maximum length `10`, accepts only Array (ex. `[(44 | 0x80000000) >>> 0, (1815 | 0x80000000) >>> 0, (0
just so you know, with pool owner support the witness path became optional if the tx is a stake pool registration one, otherwise it's still required

2020-12-02 17:58 UTC, refi93 commented on docs/signTransaction.md
> +* `type` - *required* `number` Certificate type.
probably worth elaborating on the supported certificate types and giving examples of respective certificate structures, should be available in the integration tests

2020-12-02 18:47 UTC, refi93 requested changes
see comments

2020-12-04 12:45 UTC, janmazak commented on docs/getPublickey.md
> +## Cardano: get public key
Just a note: the commit 527e5b0fa0ab31b37395808248cef01875ed0eae 
(already on branch develop) includes bulk key export (getExtendedPublicKeys).

Apart from including it in the docs, we might want to mark getExtendedPublicKey as deprecated since it we are only keeping it for backwards compatibility.

2020-12-08 21:45 UTC, refi93 commented
@jmuravsky as per https://github.com/vacuumlabs/ledgerjs-cardano-shelley/pull/20 the develop branch has been rebased, you just need to rebase to the new develop with `git rebase -i develop` and drop whatever commits do not belong to this PR, as code-wise the current develop is practically the same

2020-12-11 05:14 UTC, darko-mijic commented
Any chance this gets merged by mid-day on Monday?

2020-12-11 15:27 UTC, refi93 approved these changes

2020-12-11 15:30 UTC, refi93 commented
@darko-mijic yes, we are merging the PR right now. It won't contain docs for stake pool registration yet, but other than that, the rest is documented and we'll add the pool registration docs later, probably during the next week

2020-12-11 15:31 UTC, merged