Multiassets
vacuumlabs/ledgerjs-cardano-shelley pull request #27
Opened 2021-01-28 01:12 UTC by janmazak

Not 100% finished and needs some polishing.

2021-01-28 10:06 UTC, refi93 commented on src/Ada.js
> +export type TokenAmount =
in Trezor we ended up renaming the the entities to remain closer to the developer docs terminology (https://developers.cardano.org/en/development-environments/native-tokens/native-tokens-glossary/), now it's:

TokenGroup -> AssetGroup
TokenAmount -> Token
tokenAmounts -> tokens

Trezor protobuf definitions for reference: https://github.com/trezor/trezor-firmware/blob/master/common/protob/messages-cardano.proto#L149

2021-01-28 10:32 UTC, refi93 commented on src/Ada.js
> +        utils.uint8_to_buf(
If I understand correctly this is a breaking change, so don't forget to check for the proper version of the Ledger app. We can also add some backward-compatibility hacks, but this is probably a good opportunity to do a clean cut

2021-01-28 10:36 UTC, refi93 commented on src/Ada.js
> +    if (ttlStr)
I'd wrap it in curly braces for the sake of maintainability/consistency, same for validityIntervalStartStr

2021-01-28 10:42 UTC, refi93 commented on src/cardano.js
> +  if ((validityIntervalStartStr !== null) && (validityIntervalStartStr !== undefined)) {
`validityIntervalStartStr != null` is a more concise way to express the same

https://stackoverflow.com/questions/2559318/how-to-check-for-an-undefined-or-null-variable-in-javascript

2021-01-28 10:47 UTC, refi93 commented on src/utils.js
>  export function amount_to_buf(amount: string): Buffer {
given that we are introducing token amounts which are not subject to the same constraints as ada amounts it imho makes sense to rename this to `ada_amount_to_buf` - or just drop the check for max lovelace supply for the sake of simplicity - TBH I don't see that much added value in the check as that's the responsibility of the blockchain and may not even be true for some testnets

2021-01-28 12:02 UTC, refi93 requested changes
see comments

2021-01-29 12:18 UTC, janmazak commented on src/utils.js
>  export function amount_to_buf(amount: string): Buffer {
Well, it only reflects the check that Ledger is doing. We might consider dropping it there. 
(I think the check is there partially for added protection against attacks --- not much, of course, but every assert and validation makes the life of an attacker trying to corrupt the memory harder.)

2021-01-29 12:29 UTC, refi93 commented on src/utils.js
>  export function amount_to_buf(amount: string): Buffer {
makes sens, in the end it's a really niche corner case, so I'm ok with keeping the constraint as well though to not mix it accidentally with token amounts I'd rename it at least

2021-02-03 14:41 UTC, refi93 commented on src/Ada.js
> +    // TODO replace this with a better mechanism for detecting ledger app capabilities
I would not be afraid to centralize that in a single mapping/helper function - I did something like that in trezor-connect recently and I quite liked it, it wasn't even that much work: https://github.com/trezor/connect/commit/fe4a55cac2e7ffe1bf6b8d5af55ad83f767b6460

2021-02-03 15:13 UTC, refi93 commented on src/Ada.js
> +        confirmP1 = 0x09; // needed for backward compatibility
I'd name that constant P1_STAGE_CONFIRM_LEGACY - even if it's "backwards compatibility" code better keep basic readability

2021-02-03 15:23 UTC, refi93 commented on src/cardano.js
> +    utils.uint8_to_buf(outputType),
what's the reason behind reordering the parameters in this APDU respective to the old version? Wouldn't be the backwards-compatibility logic be less ugly, not requiring the splitting into two separate functions?

2021-02-03 15:25 UTC, refi93 requested changes
see comments

2021-02-03 16:10 UTC, refi93 commented
tested with Ledger fw 2.0.4 (a0bf957d1a919f64427dc13680e350cbe3945fdc) and 2.1.0 (d031a6d18e988537e90792fd40a13294528ca40f)  and works as expected (i.e. only features not supported in those releases fail, the rest passes)

2021-02-04 16:07 UTC, janmazak commented on src/cardano.js
> +    utils.uint8_to_buf(outputType),
I find the order "ada amount, address, tokenAmounts" rather unintuitive and prefer address, ada amount, token amounts. The temporary need for backwards compatibility does not change this preference.

2021-02-04 17:18 UTC, PeterBenc commented on src/utils.js
> +  Precondition.checkIsUint64(i, "invalid uint64 value");
One of the `cardano-hw-cli` tests fails because it has ADA amount bigger than an integer.

2021-02-05 12:58 UTC, janmazak commented on src/Ada.js
> +    // TODO replace this with a better mechanism for detecting ledger app capabilities
I don't have a clear picture of this in my mind, so I would rather leave it as it is for this release, and tackle it in the subsequent refactoring.

2021-02-05 15:46 UTC, refi93 commented on src/utils.js
> +  Precondition.checkIsUint64(i, "invalid uint64 value");
will be fixed by merging #29

2021-02-05 17:02 UTC, merged